name: alhadiqa
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  modal_progress_hud_nsn: ^0.5.1
  get_storage: ^2.1.1
  adaptive_dialog: ^2.4.1
  intl: ^0.20.0
  google_fonts: 
  linear_progress_bar: ^1.2.0
  simple_circular_progress_bar: ^1.0.2
  awesome_notifications: ^0.10.1
  awesome_notifications_fcm: ^0.10.1
  awesome_notifications_core: ^0.10.1
  badges: ^3.1.2
  rxdart: ^0.28.0
  flutter_islamic_icons: ^1.0.2
  provider: ^6.1.5
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
    
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/alhadiq_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/alhadiq_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/alhadiq_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/alhadiq_icon.png"

flutter:

  uses-material-design: true

  assets:
    - images/
  
  #fonts:
    
